apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    global:
      proxy:
        resources:
          limits:
            cpu: "250m"
            memory: "200Mi"
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        resources:
          limits:
            memory: "200Mi"
            cpu: "250m"